import type { GalleryImage, Testimonial } from '@/types'

export const GALLERY_IMAGES: GalleryImage[] = [
  {
    id: 'matrimonio-1',
    src: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&h=600&fit=crop',
    alt: 'Sposi al tramonto in Sicilia',
    category: 'matrimoni',
    title: 'Matrimonio Sofia & Marco',
    description: 'Momento romantico al tramonto con vista sul mare',
    aspectRatio: 3 / 2,
  },
  {
    id: 'matrimonio-2',
    src: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=800&fit=crop',
    alt: 'Dettaglio anelli matrimoniali',
    category: 'matrimoni',
    title: 'I Dettagli',
    description: 'La bellezza nei piccoli momenti',
    aspectRatio: 1 / 1,
  },
  {
    id: 'matrimonio-3',
    src: 'https://images.unsplash.com/photo-1544078751-58fee2d8a03b?w=800&h=600&fit=crop',
    alt: 'Sposi che ballano',
    category: 'matrimoni',
    title: 'La Festa',
    description: 'Gioia e celebrazione del grande giorno',
    aspectRatio: 3 / 2,
  },
  {
    id: 'matrimonio-4',
    src: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=600&h=800&fit=crop',
    alt: 'Cerimonia in chiesa',
    category: 'matrimoni',
    title: 'Il Momento Sacro',
    description: 'L&apos;intimità della promessa',
    aspectRatio: 2 / 3,
  },
  {
    id: 'ritratti-1',
    src: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=800&fit=crop',
    alt: 'Ritratto donna in bianco e nero',
    category: 'ritratti',
    title: 'Studio Portrait',
    description: 'Bellezza classica e senza tempo',
    aspectRatio: 2 / 3,
  },
  {
    id: 'ritratti-2',
    src: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=600&fit=crop',
    alt: 'Famiglia felice al tramonto',
    category: 'ritratti',
    title: 'Family Session',
    description: 'Amore familiare catturato nel tempo',
    aspectRatio: 3 / 2,
  },
  {
    id: 'ritratti-3',
    src: 'https://images.unsplash.com/photo-1544078751-58fee2d8a03b?w=600&h=800&fit=crop',
    alt: 'Coppia intimità in nature',
    category: 'ritratti',
    title: 'Engagement Session',
    description: 'Connessione autentica tra due persone',
    aspectRatio: 2 / 3,
  },
  {
    id: 'events-1',
    src: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=800&h=600&fit=crop',
    alt: 'Gala event illuminato',
    category: 'events',
    title: 'Corporate Gala',
    description: 'Atmosfera elegante di un evento esclusivo',
    aspectRatio: 3 / 2,
  },
  {
    id: 'events-2',
    src: 'https://images.unsplash.com/photo-1519167534503-3DF1D3260904?w=800&h=800&fit=crop',
    alt: 'Battesimo in chiesa',
    category: 'events',
    title: 'Cerimonia Battesimo',
    description: 'Momenti di gioia familiare',
    aspectRatio: 1 / 1,
  },
  {
    id: 'events-3',
    src: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=800&h=600&fit=crop',
    alt: 'Party con decorazioni',
    category: 'events',
    title: 'Private Party',
    description: 'Celebrazione in intimità',
    aspectRatio: 3 / 2,
  },
  {
    id: 'commercial-1',
    src: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=600&fit=crop',
    alt: 'Prodotto luxury lifestyle',
    category: 'commercial',
    title: 'Product Photography',
    description: 'Dettagli che raccontano qualità',
    aspectRatio: 3 / 2,
  },
  {
    id: 'commercial-2',
    src: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=800&fit=crop',
    alt: 'Fashion jewelry lifestyle',
    category: 'commercial',
    title: 'Fashion & Lifestyle',
    description: 'Bellezza e eleganza nel dettaglio',
    aspectRatio: 2 / 3,
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    author: 'Sofia & Marco',
    role: 'Sposi - Matrimonio 2024',
    content: 'Antonio ha catturato il nostro amore con una sensibilità incredibile. Le foto sono capolavori che conserveremo per tutta la vita.',
    rating: 5,
  },
  {
    id: 'test-2',
    author: 'Giulia Rossi',
    role: 'Direttrice Ufficio Stampa',
    content: 'Professionista impeccabile. Ha saputo creare un&apos;atmosfera di fiducia che ha fatto emergere la bellezza autentica nei dettagli.',
    rating: 5,
  },
  {
    id: 'test-3',
    author: 'Massimo Ferrari',
    role: 'CEO Gioielleria Ferrari',
    content: 'Le foto dei nostri prodotti hanno aumentato le vendite online del 40%. Antonio capisce il valore estetico del lusso.',
    rating: 5,
  },
]